---
version: 2
plan:
  project-key: AJL
  key: FLTRDWNLTESTS
  name: filters-downloader - test

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            docker build \
              --file Dockerfile \
              --progress plain \
              --target test-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/cleanup.sh ""
  requirements:
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
