name: Mirror

description: Mirrors code to the public repo on every push to master.

on:
  push:
    branches:
      - master

permissions:
  # checkout source repo
  contents: read
  # disable workflows in the public mirror
  actions: write
  # Octopass token for push to public repo
  id-token: write

jobs:
  mirror:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/mirror.yml@master
    with:
      team: extensions
      target_repo: git@github.com:AdguardTeam/FiltersDownloader.git
    secrets: inherit
